name: Daily Commit

on:
  schedule:
    - cron: '12 16 * * *'  # Her gün 16.12'de otomatik commit 

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name "Emir N."
          git config user.email "rakrime_262@hotmail.com"

      - name: Make an empty commit
        run: |
          date >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
