name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Her gün UTC 2:30'da çalışır

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make an empty commit
        run: |
          git config user.name "Emir N."
          git config user.email "rakrime_262@hotmail.com"  # E-posta adresinizi buraya ekleyin
          date >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit"
          git push
